OKTA_CLIENT_ID: "0oa1cf9jyxm5LJMzA357"
OKTA_CLIENT_SECRET: "Sb92_HBXMmmCpbj8N0B7evnJ8R_MvS9opN-6Coij"
OKTA_ORG: "Devsinc"
OKTA_DOMAIN: "oktapreview"
OKTA_URL: "https://dev-180006.okta.com"
OKTA_ISSUER: "https://dev-180006.okta.com/oauth2/default"
OKTA_AUTH_SERVER_ID: "default"
OKTA_REDIRECT_URI: "http://localhost:3000/users/auth/oktaoauth/callback"

PUBLISHABLE_KEY: "pk_test_5w2QiT8pnzcLSzxyDBpNNdCA00SSc6AoX7"
SECRET_KEY: "sk_test_sczHYDHVIYPbTUkOJpjYLou600UJtH5Gev"